[project]
# Top-level settings
site_name = "Apteco Help Hub"
site_url = "https://help.apteco.com/"
site_description = "The Apteco Help Hub is the official documentation site for Apteco software products."
site_author = "Rhys Vaughan"
copyright = """Copyright &copy; 2026 Apteco • All rights reserved."""
docs_dir = "docs"
site_dir = "site"
edit_uri = "edit/main/docs/"
use_directory_urls = true
# Repository information
repo_name = "Apteco/help-hub"
repo_url = "https://github.com/rhys-vaughan/zentest"
# Extra CSS
extra_css = ["stylesheets/extra.css"]

# Navigation structure
nav = [
   { "Home" = "index.md" },
   { Orbit = [
      "orbit/index.md",
      { "Getting started" = "orbit/getting-started/index.md" },
      { "Connect" = [
         "orbit/connect/index.md",
         { "Data sources" = [
            "orbit/connect/data-sources/index.md",
            "orbit/connect/data-sources/file-upload.md",
            "orbit/connect/data-sources/amazon-s3.md",
         ]}
      ]},
      { "Dashboards" = [
         "orbit/dashboards/index.md",
         { "Creating a dashboard" = "orbit/dashboards/create/index.md" },
         { "Tiles" = "orbit/dashboards/tiles/index.md" },
      ]},
      { "Audiences" = [
         "orbit/audiences/index.md",
            { "Creating an audience" = "orbit/audiences/create/index.md" },
      ]},
      { "Campaigns" = [
         "orbit/campaigns/index.md",
         { "Creating a campaign" = "orbit/campaigns/create/index.md" },
      ]},
      { "Orin AI assistant" = "orbit/orin/index.md"},
   ]},

   { "FastStats" = [
      "faststats/index.md",
      { "Getting started" = "faststats/getting-started/index.md" },
      { "Analysis" = "faststats/analysis/index.md" },
      { "Visualisation" = "faststats/visualisation/index.md" },
      { "Modelling" = "faststats/modelling/index.md"},
      { "Expressions" = "faststats/expressions/index.md"},
      { "Wizards and Virtual Variables" = "faststats/wizards-and-virtual-variables/index.md"},
      { "Cascade" = "faststats/cascade/index.md"},
   ]},

   { "PeopleStage" = [
      "peoplestage/index.md",
      { "Getting started" = "peoplestage/getting-started/index.md" },
      { "Campaigns" = "peoplestage/campaigns/index.md" },
      { "Customisation" = "peoplestage/customisation/index.md" },
      { "Responses" = "peoplestage/responses/index.md" },
      { "Reporting" = "peoplestage/reporting/index.md" },
      { "Integrations" = "peoplestage/integrations/index.md" },
   ]},

   { "Designer" = [
      "designer/index.md",
      { "Getting started" = "designer/getting-started/index.md" },
      { "System configuration" = "designer/system-configuration/index.md" },
      { "Data sources" = "designer/data-sources/index.md" },
      { "Table Relationships" = "designer/table-relationships/index.md" },
      { "Define Variables" = "designer/define-variables/index.md" },
      { "Folder Structure" = "designer/folder-structure/index.md" },
      { "Pre-Load Actions" = "designer/pre-load-actions/index.md" },
      { "Post-Load Actions" = "designer/post-load-actions/index.md" },
      { "Build Faststats System" = "designer/build-faststats-models/index.md" },
      { "Miscellaneous" = "designer/miscellaneous/index.md" },
   ]},

   { "Resources" = [
      "resources/index.md",
      { "Release notes" = [
         { "Orbit release notes" = [
         { "2026" = "resources/release-notes/orbit/2026.md"},
         { "2025" = "resources/release-notes/orbit/2025.md"},
         ]},
      { "FastStats release notes" = "resources/release-notes/faststats/2026.md" },
      ]},
      { "Patch notes" = "resources/patch-notes/index.md" },
      { "Technical updates" = "resources/technical-updates.md" },
      { "Apteco insider programme" = "resources/insider-programme.md" },
   ]},

   { "Admin" = [
      "admin/index.md",
      { "Requirements and prerequisites" = "admin/requirements-and-prerequisites.md" },
      { "Installation" = "admin/installation/index.md" },
      { "Configuration" = "admin/configuration/index.md" },
      { "Integration" = "admin/integration/index.md" },
      { "Security and privacy" = "admin/security-and-privacy.md" },
      { "Roles and rights" = "admin/roles-and-rights.md" },
      { "PDF technical guides" = "admin/pdf-technical-guides.md" },
   ]},

   { "apteco.com" = "https://www.apteco.com" },
]

# Extra settings
[project.extra]
# generator = false

# Project tags
[project.extra.tags]
Orbit = "Orbit"
FastStats = "FastStats"
PeopleStage = "PeopleStage" 
Designer = "Designer"
Admin = "Admin"
Resources = "Resources"

# Status labels
[project.extra.status]
new = "Recently added"
deprecated = "Deprecated"

# Socials
[[project.extra.social]]
icon = "fontawesome/solid/globe"
link = "https://www.apteco.com/"
name = "Insights into Action"
[[project.extra.social]]
icon = "fontawesome/brands/x-twitter"
link = "https://twitter.com/Apteco"
name = "Apteco on X"
[[project.extra.social]]
icon = "fontawesome/brands/linkedin"
link = "https://www.linkedin.com/company/apteco-ltd"
name = "Apteco on LinkedIn"
[[project.extra.social]]
icon = "fontawesome/brands/youtube"
link = "https://www.youtube.com/channel/UCQkp6S_RjbqtHcz2T5JU6LQ"
name = "Apteco on YouTube"
[[project.extra.social]]
icon = "fontawesome/brands/facebook"
link = "https://www.facebook.com/Apteco"
name = "Apteco on Facebook"


# Theme configuration
[project.theme]
language = "en"
custom_dir = "overrides"
options.custom_icons = ["overrides/.icons"]
logo = "assets/images/apteco-logo-icon.svg"
favicon = "assets/images/apteco-logo-icon.svg"

# Theme features
features = [
   "content.action.edit",
   "content.action.view",
   "content.code.annotate",
   "content.code.copy",
   "content.code.select",
   "content.footnote.tooltips",
   "content.tabs.link",
   "content.tooltips",
   "header.autohide",
   "search.highlight",
   "toc.follow",
   # "toc.integrate",
   # "announce.dismiss",
   "navigation.footer",
   "navigation.indexes",
   "navigation.instant",
   "navigation.instant.prefetch",
   "navigation.instant.progress",
   "navigation.path",
   "navigation.tabs",
   "navigation.top",
   "navigation.tracking",
   # "navigation.prune",
   # "navigation.sections",
   # "navigation.tabs.sticky",
   # "navigation.expand",

]

# Project fonts
font.text = "Poppins"
font.code = "JetBrains Mono"

# Project icons
[project.theme.icon]
admonition = {note = "lucide/square-pen", example = "lucide/book-open-text"}

# Palette toggle for light mode
[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "custom"

# Palette toggle for dark mode
[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
