[project]
# =========================================
# Top-level settings
# =========================================
site_name = "Apteco docs"
site_url = "https://help.apteco.com/"
site_description = "Official documentation site for Apteco software products."
site_author = "Rhys Vaughan"
copyright = " &copy; Apteco 2026 &nbsp; All rights reserved. &nbsp; | &nbsp; <a href='https://www.apteco.com/privacy-policy' target='_blank'>Privacy policy</a> &nbsp; | &nbsp; <a href='https://status.apteco.com/' target='_blank'>System status</a> &nbsp; | &nbsp; <a href='https://www.apteco.com/community/find-a-partner' target='_blank'>Partner directory</a> &nbsp; | &nbsp; <a href='https://www.apteco.com/products/pricing' target='_blank'>Pricing</a> &nbsp; | &nbsp; <a href='https://www.apteco.com/contact' target='_blank'>Contact us</a>"
docs_dir = "docs"
site_dir = "site"
use_directory_urls = true
extra_css = ["assets/stylesheets/extra.css"]
extra_javascript = ["assets/javascripts/extra.js"]


# =========================================
# Navigation structure
# =========================================
nav = [
   { "Home" = "index.md" },
   { "Orbit" = [
      "orbit/index.md",
      { "Getting started" = "orbit/getting-started.md" },
      { "Connect" = [
         "orbit/connect/index.md",
         { "Data sources" = [
            "orbit/connect/data-sources/index.md",
            "orbit/connect/data-sources/file.md",
            "orbit/connect/data-sources/amazon-s3.md",
            "orbit/connect/data-sources/salesforce.md",
         ]}
      ]},
      { "Dashboards" = [
         "orbit/dashboards/index.md",
         { "Creating a dashboard" = "orbit/dashboards/create/index.md" },
         { "Tiles" = [
            "orbit/dashboards/tiles/index.md",
            { "ROI number tile" = "orbit/dashboards/tiles/roi.md" },
         ]},
         { "Filters" = [
            "orbit/dashboards/filters/index.md",
            { "Analysis filters" = "orbit/dashboards/filters/analysis.md" },
         ]},
      ]},
      { "Audiences" = [
         "orbit/audiences/index.md",
            { "Creating an audience" = "orbit/audiences/create/index.md" },
      ]},
      { "Campaigns" = [
         "orbit/campaigns/index.md",
         { "Creating a campaign" = "orbit/campaigns/create/index.md" },
         { "Quick messages" = "orbit/campaigns/quick-messages.md" },
         { "Apteco email" = "orbit/campaigns/apteco-email/index.md" },
         { "UTM code tracking" = "orbit/campaigns/utm.md" },
      ]},
      { "Orin AI assistant" = "orbit/orin/index.md"},
   ]},

   { "FastStats" = [
      "faststats/index.md",
      { "Getting started" = "faststats/getting-started.md" },
      { "Analysis" = "faststats/analysis/index.md" },
      { "Visualisation" = "faststats/visualisation/index.md" },
      { "Modelling" = "faststats/modelling/index.md"},
      { "Expressions" = "faststats/expressions/index.md"},
      { "Wizards and virtual variables" = "faststats/wizards-and-virtual-variables/index.md"},
      { "Cascade" = "faststats/cascade/index.md"},
   ]},

   { "PeopleStage" = [
      "peoplestage/index.md",
      { "Getting started" = "peoplestage/getting-started.md" },
      { "Campaigns" = "peoplestage/campaigns/index.md" },
      { "Customisation" = "peoplestage/customisation/index.md" },
      { "Responses" = "peoplestage/responses/index.md" },
      { "Reporting" = "peoplestage/reporting/index.md" },
      { "Integration" = "peoplestage/integration/index.md" },
   ]},

   { "Designer" = [
      "designer/index.md",
      { "Getting started" = "designer/getting-started.md" },
      { "System configuration" = "designer/system-configuration/index.md" },
      { "Data sources" = "designer/data-sources/index.md" },
      { "Table relationships" = "designer/table-relationships/index.md" },
      { "Define variables" = "designer/define-variables/index.md" },
      { "Folder structure" = "designer/folder-structure/index.md" },
      { "Pre-load actions" = "designer/pre-load-actions/index.md" },
      { "Post-load actions" = "designer/post-load-actions/index.md" },
      { "Build FastStats system" = "designer/build-faststats-system/index.md" },
      { "Miscellaneous" = "designer/miscellaneous/index.md" },
   ]},

   { "Resources" = [
      "resources/index.md",
      { "Getting started" = "resources/getting-started.md" },
      { "Release notes" = [
         "resources/release-notes/index.md",
         { "Orbit release notes" = [
         { "2026" = "resources/release-notes/orbit/2026.md"},
         { "2025" = "resources/release-notes/orbit/2025.md"},
         ]},
      { "FastStats release notes" = "resources/release-notes/faststats/2026.md" },
      ]},
      { "Patches" = "resources/patches/index.md" },
      { "Technical updates" = "resources/tech-updates/index.md" },
      { "Apteco insider programme" = "resources/insider-programme.md" },
      { "Useful contacts" = "resources/contact.md" },
      { "Technical services" = "resources/support.md" },
      { "Training" = "resources/training.md" },
   ]},

   { "Admin" = [
      "admin/index.md",
      { "Requirements and prerequisites" = "admin/requirements-and-prerequisites/index.md" },
      { "Installation" = "admin/installation/index.md" },
      { "Configuration" = "admin/configuration/index.md" },
      { "Integration" = "admin/integration/index.md" },
      { "Security and privacy" = "admin/security-and-privacy/index.md" },
      { "PDF technical guides" = "admin/pdf-technical-guides/index.md" },
   ]},

   { "apteco.com" = "https://www.apteco.com" },
]

# =========================================
# Repository information
# =========================================
#repo_name = "Apteco/help-hub"
#repo_url = "https://github.com/rhys-vaughan/zentest"
#edit_uri = "edit/main/docs/"

[project.extra]

# =========================================
# Generator notice
# =========================================
#generator = false

# =========================================
# Project tags
# =========================================
[project.extra.tags]
Orbit = "Orbit"
FastStats = "FastStats"
PeopleStage = "PeopleStage" 
Designer = "Designer"
Admin = "Admin"
Resources = "Resources"

# =========================================
# Status labels
# =========================================
[project.extra.status]
new = "Recently added"
deprecated = "Deprecated"

# =========================================
# Socials
# =========================================
[[project.extra.social]]
icon = "fontawesome/solid/globe"
link = "https://www.apteco.com/"
name = "Insights into Action"
[[project.extra.social]]
icon = "fontawesome/brands/x-twitter"
link = "https://twitter.com/Apteco"
name = "Apteco on X"
[[project.extra.social]]
icon = "fontawesome/brands/linkedin"
link = "https://www.linkedin.com/company/apteco-ltd"
name = "Apteco on LinkedIn"
[[project.extra.social]]
icon = "fontawesome/brands/youtube"
link = "https://www.youtube.com/channel/UCQkp6S_RjbqtHcz2T5JU6LQ"
name = "Apteco on YouTube"
[[project.extra.social]]
icon = "fontawesome/brands/facebook"
link = "https://www.facebook.com/Apteco"
name = "Apteco on Facebook"

# =========================================
# Theme configuration
# =========================================
[project.theme]
language = "en"
custom_dir = "overrides"
options.custom_icons = ["overrides/.icons"]
logo = "assets/images/apteco-logo-icon.svg"
favicon = "assets/images/apteco-logo-icon.svg"

# =========================================
# Theme features
# =========================================
features = [
   #"content.action.edit",
   #"content.action.view",
   "content.code.annotate",
   "content.code.copy",
   "content.code.select",
   "content.footnote.tooltips",
   "content.tabs.link",
   "content.tooltips",
   "header.autohide",
   "search.highlight",
   "toc.follow",
   #"toc.integrate",
   "announce.dismiss",
   "navigation.footer",
   "navigation.indexes",
   "navigation.instant",
   "navigation.instant.prefetch",
   "navigation.instant.progress",
   "navigation.path",
   "navigation.tabs",
   "navigation.top",
   "navigation.tracking",
   "navigation.prune",
   #"navigation.sections",
   #"navigation.tabs.sticky",
   #"navigation.expand",
]

# =========================================
# Project fonts
# =========================================
font.text = "Poppins"
font.code = "JetBrains Mono"

# =========================================
# Project icons
# =========================================
[project.theme.icon]
admonition = {note = "lucide/square-pen", example = "lucide/book-open-text", success = "lucide/rocket"}

# =========================================
# Pallettes and palette toggles
# =========================================
# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"
# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "custom"
# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
